module.exports = {
    host : "http://118.25.104.28:2018",
    login : "/login",
    register : "/register",
    actDetail : "/projDetail",
    actList : "/ProjList",
    upload:"/upload",
    userInfo: "/infoMe",
    joinAct:"/joinProj",
    updateProj:"/updateProj",
    addProjFile:"/addProjFile",
    getProjFile:"/getProjFile",
    manageFile:"/manageFile",
    answer:"/ansQue",
    getParterDetail:"/getParterDetail",
    scoreEveryOne:"/addScoreArray",
}